//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_NEW_NEW
    {
        public int ID { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public string ABOUT { get; set; }
        public string GENDER { get; set; }
        public string EMAIL { get; set; }
        public string SECRET_Q { get; set; }
        public string SECRET_A { get; set; }
    }
}
